require('@babel/register')({ presets: [[(require('./paths').APP + '/node_modules/@babel/preset-env'), { targets: { node: 'current' } }]], babelrc:false, configFile:false, extensions:['.js'], cache:false, only:[/app\/client\/utils/] });
const N = require((require('./paths').APP + '/client/utils/updateNotice.js'));
const t = (label, ok) => console.log((ok ? 'OK  ' : 'MISS') + ' ' + label);
const MIN = 10 * 60 * 1000;
t('first check at the start is allowed', N.canCheck('beta', 0, 1000000));
t('"Off" never checks', !N.canCheck('off', 0, 1e12));
t('coming back to the window within 10 minutes: no new request (GitHub allows only 60 an hour)', !N.canCheck('beta', 1000, 1000 + MIN - 1));
t('...after 10 minutes: yes', N.canCheck('beta', 1000, 1000 + MIN));
t('stable-only and beta both check', N.canCheck('stable', 0, 1e9) && N.canCheck('beta', 0, 1e9));
const up = { available: true, kind: 'files', sha: 'abc1234', version: 'abc1234' };
const rel = { available: true, kind: 'release', version: 'v2.1', prerelease: false };
const no = () => false;
t('a new upload is announced', N.shouldAnnounce(up, '', no));
t('...but only once while SSGL is open (same upload again: no)', !N.shouldAnnounce(up, N.noticeKey(up), no));
t('...a NEWER upload is announced again', N.shouldAnnounce({ ...up, sha: 'def5678' }, N.noticeKey(up), no));
t('...an upload you said "not now" to stays quiet', !N.shouldAnnounce(up, '', sha => sha === 'abc1234'));
t('"not now" for an upload does not silence a release', N.shouldAnnounce(rel, '', () => true));
t('nothing new -> nothing announced', !N.shouldAnnounce({ available: false }, '', no) && !N.shouldAnnounce(null, '', no));
t('visible: beta+stable shows uploads, releases and beta releases', N.isVisible('beta', up) && N.isVisible('beta', rel) && N.isVisible('beta', { ...rel, prerelease: true }));
t('visible: stable only shows stable releases, not beta releases and not uploads', N.isVisible('stable', rel) && !N.isVisible('stable', { ...rel, prerelease: true }) && !N.isVisible('stable', up));
t('visible: off shows nothing', !N.isVisible('off', up) && !N.isVisible('off', rel));
t('visible: nothing available -> nothing', !N.isVisible('beta', { available: false }) && !N.isVisible('beta', undefined));
