require('@babel/register')({ presets: [[(require('./paths').APP + '/node_modules/@babel/preset-env'), { targets: { node: 'current' } }]], babelrc:false, configFile:false, extensions:['.js'], cache:false, only:[/app\/client\/utils/] });
const { sectionOfFolder, sectionOf, groupBySection, SECTION_NUMBER } = require((require('./paths').APP + '/client/utils/sections.js'));
const t = (label, ok) => console.log((ok ? 'OK  ' : 'MISS') + ' ' + label);
const yours = { '1_BP': 'main', '2_ GLORY KILLS': 'glory', '3_MONSTERS': 'monsters', '4_GAMEPLAY': 'gameplay', '5_WEAPONS': 'weapons', '6_SOUNDS': 'sounds', '7_VISUAL': 'visual', '8_UPSCALE': 'textures' };
Object.keys(yours).forEach(k => t('your folder "' + k + '" -> ' + yours[k], sectionOfFolder(k) === yours[k]));
const more = { '0_LIBRARIES': 'libraries', 'Libs': 'libraries', '9_PATCHES': 'patches', 'Compatibility patches': 'patches', 'Music': 'music', 'Soundtrack': 'music', 'OST': 'music', 'Sound effects': 'sounds', 'Weapon sounds': 'sounds', 'HD textures': 'textures', 'Upscaled flats': 'textures', 'Lighting': 'visual', 'HUD': 'visual', 'Shaders': 'visual', 'Project Brutality': 'main', 'Main mod': 'main', 'Enemies': 'monsters', 'Executions': 'glory', 'Tweaks': 'gameplay', 'random stuff': 'other', 'litdoom': 'other', '': 'other', 'maps': 'other' };
Object.keys(more).forEach(k => t('"' + k + '" -> ' + more[k], sectionOfFolder(k) === more[k]));
t('"soundtrack" is music, not sounds', sectionOfFolder('Soundtrack') === 'music');
t('a folder that merely CONTAINS a word inside another word is not matched ("mainstream" is not "main")', sectionOfFolder('upbase') === 'other' && sectionOfFolder('hudson') === 'other');
t('maps always are the maps section', sectionOf({ isMap: true, folders: ['3_MONSTERS'] }) === 'maps');
t('mod without a folder -> other', sectionOf({ folders: [], folder: '' }) === 'other');
t('the folder CLOSEST to the mod decides', sectionOf({ folders: ['5_WEAPONS', '3_MONSTERS'] }) === 'monsters');
t('unknown top folder: the deeper folder name decides ("Mods/3_MONSTERS")', sectionOf({ folders: ['Mods', '3_MONSTERS'] }) === 'monsters');
const bd = 'Brutal Doom Black Edetion';
t('YOUR CASE: "Brutal Doom Black Edetion / 10_VISUAL" -> visual (not main)', sectionOf({ folders: [bd, '10_VISUAL'] }) === 'visual');
t('YOUR CASE: "... / 9_TEXTURES" -> textures', sectionOf({ folders: [bd, '9_TEXTURES'] }) === 'textures');
t('YOUR CASE: "... / 11_PATCHES" -> patches', sectionOf({ folders: [bd, '11_PATCHES'] }) === 'patches');
t('YOUR CASE: a mod right in "Brutal Doom Black Edetion" -> main', sectionOf({ folders: [bd] }) === 'main');
t('closest folder says nothing -> the next one up is used', sectionOf({ folders: [bd, 'random stuff'] }) === 'main' && sectionOf({ folders: ['5_WEAPONS', 'litdoom'] }) === 'weapons');
t('numbers shown in the titles: libraries 0 ... maps 11, other has none', SECTION_NUMBER.libraries === 0 && SECTION_NUMBER.maps === 11 && SECTION_NUMBER.other === undefined);

const mk = (id, folder, extra = {}) => ({ id, folders: folder ? [folder] : [], folder, ...extra });
const mods = [mk('a', '1_BP'), mk('b', '3_MONSTERS'), mk('c', '3_MONSTERS'), mk('d', '5_WEAPONS'), mk('e', '3_MONSTERS'), mk('f', '', {}), mk('m', 'Ep1', { isMap: true })];
let g = groupBySection(['a', 'b', 'c', 'd', 'e', 'f', 'm'], mods);
t('groups follow the load order: main | monsters(2) | weapons | monsters | other | maps', g.map(x => x.section + ':' + x.entries.length).join(' | ') === 'main:1 | monsters:2 | weapons:1 | monsters:1 | other:1 | maps:1');
t('the same section twice (not next to each other) = two groups, nothing is moved', g.filter(x => x.section === 'monsters').length === 2);
t('every entry keeps its place in the load order (index)', g.reduce((all, x) => all.concat(x.entries.map(e => e.index)), []).join() === '0,1,2,3,4,5,6');
g = groupBySection(['a', 'gone', 'b'], mods);
t('a mod that is not found stays with the group before it', g.map(x => x.section + ':' + x.entries.map(e => e.id).join('+')).join(' | ') === 'main:a+gone | monsters:b');
g = groupBySection(['gone', 'a'], mods);
t('missing mod at the very start -> "other" group, then main', g.map(x => x.section).join() === 'other,main');
t('empty load order -> no groups', groupBySection([], mods).length === 0);
